forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-apt',
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod 'puppetlabs-apache',
  :git => "git://github.com/puppetlabs/puppetlabs-apache.git"
